pipeline:
  name: cf-platform-pipeline

  git:
    owner: starkandwayne
    repo:  demo-cf-deployments
    branch: latest-cf-aws-codex
    private_key: (( vault "concourse/demo/cf/github:private_key" ))

  vault:
    url:    https://10.4.1.7
    verify: no
    role: (( vault "secret/uswest2demo/full/concourse/approle/concourse:approle-id" ))
    secret: (( vault "secret/uswest2demo/full/concourse/approle/concourse:approle-secret" ))
  
  slack: 
    channel: '#botspam'
    webhook: (( vault "concourse/genesis/slack:webhook" ))

  boshes:
    dev:
      url:      https://10.4.16.4:25555
      ca_cert:  (( vault "secret/dev/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/dev/bosh/users/admin:password" ))
    uswest2demo:
      url:      https://10.4.1.4:25555
      ca_cert:  (( vault "secret/uswest2demo/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/uswest2demo/bosh/users/admin:password" ))
    
  layouts:
    default: |+
      auto *dev
      dev -> uswest2demo

jobs:
- name: internal-domain
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: dev-changes
        passed:
        - dev-cf
  - task: create-apps-internal-domain
    file: dev-changes/tasks/run-cf-cli.yml
    input_mapping:
      changes: dev-changes
    vars:
      environment: dev
      

groups:
- name: default
  jobs:
  - dev-cf
  - uswest2demo-cf

- name: features
  jobs:
  - internal-domain