pipeline:
  name: cf-platform-pipeline

  git:
    owner: starkandwayne
    repo:  demo-cf-deployments
    branch: latest-cf-aws-codex
    private_key: (( vault "concourse/demo/cf/github:private_key" ))

  #tagged: yes

  vault:
    url:    https://10.4.1.7
    verify: no
    # run setup-approle from concourse-kit deployment ex. genesis do [env] -- setup-approle
  
  slack:
    channel: '#botspam'
    webhook: (( vault "concourse/genesis/slack:webhook" ))

  boshes:
    dev:
      url:      https://10.4.16.4:25555
      ca_cert:  (( vault "secret/dev/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/dev/bosh/users/admin:password" ))
    baby-bosh:
      url:      https://10.4.63.4:25555
      ca_cert:  (( vault "secret/baby/bosh/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/baby/bosh/bosh/users/admin:password" ))
  
  layouts:
    default: |+
      auto *dev
      dev -> baby-bosh

groups:
- name: cf-platform-pipeline
  jobs:
  - ((append))
  - dev-cf-config

##### CF-MGMT stuff #####
##### dev.yml configuration #####
## CONFIGURATION VARIABLES FOR ENV ##
## cf-mgmt: $env: (...) ##
cf-mgmt:
  dev:
    git_repo_uri: "https://github.com/starkandwayne/demo-cf-deployments.git"
    git_repo_branch: master
    system_domain: "system.codex.starkandwayne.com"
    user_id: "cf_mgmt_client"
    client_secret: (( vault "secret/dev/bosh/uaa/clients/cf_mgmt_client:secret" ))
    log_level: INFO
    time-trigger: 15m
    config_dir: ci/config/dev
    ldap_server: ""
    ldap_user: ""
    ldap_password: ""
    password: ""
  baby-bosh:
    git_repo_uri: "https://github.com/starkandwayne/demo-cf-deployments.git"
    git_repo_branch: master
    system_domain: "system.codex.starkandwayne.com"
    user_id: "cf_mgmt_client"
    client_secret: (( vault "secret/dev/bosh/uaa/clients/cf_mgmt_client:secret" ))
    log_level: INFO
    time-trigger: 15m
    config_dir: ci/config/baby-bosh
    ldap_server: ""
    ldap_user: ""
    ldap_password: ""
    password: ""
#############################################
#### dev cf-mgmt pipeline configuration
#############################################
resources:
- name: dev-config-repo
  type: git
  source:
    uri: ((grab cf-mgmt.dev.git_repo_uri))
    branch: ((grab cf-mgmt.dev.git_repo_branch))
    # only watch for changes in config directory
    paths: ["ci", "((grab cf-mgmt.dev.config_dir))"]

jobs:
- name: dev-cf-config
  plan:
  - get: dev-config-repo
    trigger: true
  - get: dev-changes
    trigger: true
    passed: [dev-cf]
  - task: create-orgs
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: create-orgs

  - task: shared-domains
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: shared-domains

  - task: create-security-groups
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: create-security-groups

  - task: assign-default-security-groups
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: assign-default-security-groups

  - task: delete-orgs
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: delete-orgs

  - task: update-orgs-metadata
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-orgs-metadata

  - task: create-org-private-domains
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: create-org-private-domains

  - task: service-access
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: service-access

  - task: share-org-private-domains
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: share-org-private-domains

  - task: create-spaces
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: create-spaces

  - task: delete-spaces
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: delete-spaces

  - task: update-spaces
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-spaces

  - task: update-spaces-metadata
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-spaces-metadata

  - task: update-space-users
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LDAP_USER: ((grab cf-mgmt.dev.ldap_user))
      LDAP_PASSWORD: ((grab cf-mgmt.dev.ldap_password))
      LDAP_SERVER: ((grab cf-mgmt.dev.ldap_server))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-space-users

  - task: update-space-quotas
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-space-quotas

  - task: update-space-security-groups
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-space-security-groups

  - task: update-org-users
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LDAP_USER: ((grab cf-mgmt.dev.ldap_user))
      LDAP_PASSWORD: ((grab cf-mgmt.dev.ldap_password))
      LDAP_SERVER: ((grab cf-mgmt.dev.ldap_server))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-org-users

  - task: update-org-quotas
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-org-quotas

  - task: isolation-segments
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: isolation-segments

  - task: cleanup-org-users
    file: dev-config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: cleanup-org-users
