pipeline:
  name: cf-platform-pipeline

  git:
    owner: starkandwayne
    repo:  demo-cf-deployments
    branch: latest-cf-aws-codex
    private_key: (( vault "concourse/demo/cf/github:private_key" ))

  tagged: yes

  vault:
    url:    https://10.4.1.7
    verify: no
    role: (( vault "secret/uswest2demo/full/concourse/approle/concourse:approle-id" ))
    secret: (( vault "secret/uswest2demo/full/concourse/approle/concourse:approle-secret" ))
  
  slack:
    channel: '#botspam'
    webhook: (( vault "concourse/genesis/slack:webhook" ))

  boshes:
    dev:
      url:      https://10.4.16.4:25555
      ca_cert:  (( vault "secret/dev/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/dev/bosh/users/admin:password" ))
    uswest2demo:
      url:      https://10.4.1.4:25555
      ca_cert:  (( vault "secret/uswest2demo/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/uswest2demo/bosh/users/admin:password" ))
  
  layouts:
    default: |+
      auto *dev
      dev -> uswest2demo

jobs:
- name: configure-internal-domain
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: uswest2demo-cache
        passed:
        - dev-cf
        trigger: true
      - get: dev-changes
        passed:
        - dev-cf
        trigger: true
  - task: run-cf-cli
    file: dev-changes/tasks/run-cf-cli.yml
    input_mapping:
      changes: dev-changes
    vars:
      SCRIPT: scripts/create-apps-internal-domain.sh
      VAULT_ADDR: https://10.4.1.7
      VAULT_ROLE: (( vault "secret/uswest2demo/full/concourse/approle/concourse:approle-id" ))
      VAULT_SECRET: (( vault "secret/uswest2demo/full/concourse/approle/concourse:approle-secret" ))
      VAULT_SKIP_VERIFY: "true"

# - name: configure-security-groups
#   public: true
#   serial: true
#   plan:
#   - do:
#     - in_parallel:
#       - get: uswest2demo-cache
#         passed:
#         - dev-cf
#         trigger: true
#       - get: dev-changes
#         passed:
#         - dev-cf
#         trigger: true
#   - task: run-cf-cli
#     file: dev-changes/tasks/run-cf-cli.yml
#     input_mapping:
#       changes: dev-changes
#     vars:
#       SCRIPT: scripts/create-app-security-groups.sh
#       SCRIPT_CONFIG: >
#         [
#           {
#             name: dns
#             json_file: scripts/asg-dns.json
#             bindings: []
#             global: true
#           },
#           {
#             name: credhub_open
#             json_file: scripts/asg-credhub-open.json
#             bindings: [
#               {
#                 org: system
#                 space: nfs-broker-space
#                 lifecycle: running
#               },
#               {
#                 org: system
#                 space: smb-broker-space
#                 lifecycle: running
#               }
#             ]
#           }
#         ]
#       VAULT_ADDR: https://10.4.1.7
#       VAULT_ROLE: (( vault "secret/uswest2demo/full/concourse/approle/concourse:approle-id" ))
#       VAULT_SECRET: (( vault "secret/uswest2demo/full/concourse/approle/concourse:approle-secret" ))
#       VAULT_SKIP_VERIFY: "true"

resources:
- name: dev-changes
  source:
    paths:
    - ((append))
    - ci.yml
    - tasks
    - scripts

groups:
- name: cf-platform-pipeline
  jobs:
  - ((append))
  - configure-internal-domain


  # DEBUG task, useful to run all sort of commands ;)
  # - task: debug-only
  #   config:
  #     platform: linux
  #     image_resource:
  #       name: ""
  #       source:
  #         repository: starkandwayne/concourse
  #         tag: latest
  #       type: registry-image
  #     inputs:
  #       - name: dev-changes
  #     params:
  #       VAULT_ADDR: https://10.4.1.7
  #       VAULT_ROLE_ID: 
  #       VAULT_SECRET_ID: 
  #       VAULT_SKIP_VERIFY: "true"
  #     run:
  #       path: sh
  #       args:
  #       - -c
  #       - |
  #         cd dev-changes
  #         safe target -k $VAULT_ADDR vault
  #         safe targets
  #         {
  #           echo $VAULT_ROLE_ID
  #           echo $VAULT_SECRET_ID
  #         } | safe auth approle