platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: changes

#params:
#  current_env: ((env)) #passed via vars?

run:
  path: sh
  args:
  - -ce
  - |
    cd changes
    echo $VAULT_ADDR
    safe target -k $VAULT_ADDR vault
    safe targets
    {
      echo $VAULT_ROLE_ID
      echo $VAULT_SECRET_ID
    } | safe auth approle
    genesis info dev
