platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: changes

#params:
#  current_env: ((env)) #passed via vars?

run:
  path: sh
  args:
  - -ce
  - |
    cd changes
    ls -ltra
    safe ls /
