platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: changes

params:
  VAULT_ADDR: ((VAULT_ADDR))
  VAULT_ROLE: ((VAULT_ROLE))
  VAULT_SECRET: ((VAULT_SECRET))
  VAULT_SKIP_VERIFY: ((VAULT_SKIP_VERIFY))

run:
  path: sh
  args:
  - -ce
  - |
    cd changes
    echo $VAULT_ADDR
    VERIFY=$([ "$VAULT_SKIP_VERIFY" == "true" ] && echo "-k" || echo "")
    safe target $VERIFY $VAULT_ADDR vault
    safe targets
    {
      echo $VAULT_ROLE_ID
      echo $VAULT_SECRET_ID
    } | safe auth approle
    genesis info dev
