platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: changes

params:
  VAULT_ADDR: ((VAULT_ADDR))
  VAULT_ROLE: ((VAULT_ROLE))
  VAULT_SECRET: ((VAULT_SECRET))
  VAULT_SKIP_VERIFY: ((VAULT_SKIP_VERIFY))

run:
  path: sh
  args:
  - -ce
  - |
    cd changes
    VERIFY=$([ "$VAULT_SKIP_VERIFY" ] && echo "-k" || echo "")
    safe target $VERIFY $VAULT_ADDR vault
    {
      echo $VAULT_ROLE
      echo $VAULT_SECRET
    } | safe auth approle
    echo "Show genesis info"
    genesis info dev
    echo "Setting up CLI"
    genesis do dev -- setup-cli -f
    echo "Login to CF..."
    genesis do dev -q -- login
    echo "Checking on CF CLI"
    cf target
