platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: changes

outputs:
- name: changes-autoscale

params:
  SCRIPT: ((SCRIPT))
  ENV: ((ENV))
  VAULT_ADDR: ((VAULT_ADDR))
  VAULT_ROLE: ((VAULT_ROLE))
  VAULT_SECRET: ((VAULT_SECRET))
  VAULT_SKIP_VERIFY: ((VAULT_SKIP_VERIFY))
  GIT_BRANCH: ((GIT_BRANCH))

run:
  path: sh
  args:
  - -c
  - |
    # stop on non-0, prompt non-existing vars
    set -eu
    # do everything in task using output
    cp -r changes changes-autoscale
    BASE_PATH=$(pwd)/changes-autoscale
    cd $BASE_PATH

    # setup Vault
    VERIFY=$([ "$VAULT_SKIP_VERIFY" ] && echo "-k" || echo "")
    safe target $VERIFY $VAULT_ADDR vault
    {
      echo $VAULT_ROLE
      echo $VAULT_SECRET
    } | safe auth approle
    echo ">> Show genesis info"
    genesis info $ENV -q
    echo ">> Setting up CLI"
    genesis do $ENV -q -- setup-cli -f
    echo ">> Login to CF..."
    genesis do $ENV -q -- login
    cd "$BASE_PATH/ci/config/$ENV"

    # Execute script passed using $BASE_PATH to solve relative pathing inside script
    # e.g. BASH_SOURCE[0] checking
    echo ">> Running \".$BASE_PATH/$SCRIPT\" against CF..."
    bash $BASE_PATH/$SCRIPT

    # if all good lets commit that
    git add .
    git config user.name "Concourse Bot"
    git config user.email "concourse@pipeline"
    git commit -m "[AUTOSCALE] Push latest results of cf_scale"

    git status

    #CURRENT: lets try to use put task instead of manual push
    # echo ">> Setting ssh known_hosts"
    # SHA=$(ssh-keyscan -t ecdsa github.com 2>&1 |ssh-keygen -lf - | grep -E -o 'SHA256:[0-9a-zA-Z/]+')
    # if ["$SHA" == "SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM"]; then
    #   echo "Matched proper SHA256 for github"
    #   ssh-keyscan -t ecdsa github.com >> ~/.ssh/known_hosts
    # else
    #   echo "SHA fetched from github.com doesn't match! It may be a MITM attempt!"
    #   exit 1
    # fi
    
    # # rebase, as there is non-0 chance something will be commited between our commit
    # git pull -r origin $GIT_BRANCH
    # git push
