platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: changes

params:
  SCRIPT: ((SCRIPT))
  ENV: ((ENV))
  VAULT_ADDR: ((VAULT_ADDR))
  VAULT_ROLE: ((VAULT_ROLE))
  VAULT_SECRET: ((VAULT_SECRET))
  VAULT_SKIP_VERIFY: ((VAULT_SKIP_VERIFY))

run:
  path: sh
  args:
  - -ce
  - |
    BASE_PATH=$(pwd)/changes
    cd $BASE_PATH

    VERIFY=$([ "$VAULT_SKIP_VERIFY" ] && echo "-k" || echo "")
    safe target $VERIFY $VAULT_ADDR vault
    {
      echo $VAULT_ROLE
      echo $VAULT_SECRET
    } | safe auth approle
    echo ">> Show genesis info"
    genesis info $ENV -q
    echo ">> Setting up CLI"
    genesis do $ENV -q -- setup-cli -f
    echo ">> Login to CF..."
    genesis do $ENV -q -- login
    cd "$BASE_PATH/ci/config/$ENV"
    echo ">> Running \".$BASE_PATH/$SCRIPT\" against CF..."
    bash $BASE_PATH/$SCRIPT
