platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: changes

outputs:
- name: changes-autoscale

params:
  SCRIPT: ((SCRIPT))
  ENV: ((ENV))
  VAULT_ADDR: ((VAULT_ADDR))
  VAULT_ROLE: ((VAULT_ROLE))
  VAULT_SECRET: ((VAULT_SECRET))
  VAULT_SKIP_VERIFY: ((VAULT_SKIP_VERIFY))
  GIT_BRANCH: ((GIT_BRANCH))

run:
  path: sh
  args:
  - -c
  - |
    # stop on non-0, prompt non-existing vars
    set -eu
    BASE_PATH=$(pwd)/changes
    cd $BASE_PATH

    VERIFY=$([ "$VAULT_SKIP_VERIFY" ] && echo "-k" || echo "")
    safe target $VERIFY $VAULT_ADDR vault
    {
      echo $VAULT_ROLE
      echo $VAULT_SECRET
    } | safe auth approle
    echo ">> Show genesis info"
    genesis info $ENV -q
    echo ">> Setting up CLI"
    genesis do $ENV -q -- setup-cli -f
    echo ">> Login to CF..."
    genesis do $ENV -q -- login
    cd "$BASE_PATH/ci/config/$ENV"
    echo ">> Running \".$BASE_PATH/$SCRIPT\" against CF..."
    bash $BASE_PATH/$SCRIPT

    # if all good lets commit that
    git add .

    git config user.name "Concourse Bot"
    git config user.email "concourse@pipeline"
    git commit -m "[AUTOSCALE] Push latest results of cf_scale"

    # rebase, as there is non-0 chance something will be commited between our commit
    git pull -r origin $GIT_BRANCH
    echo "yes" | git push
