platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: changes

run:
  path: sh
  args:
  - -ce
  - |
    uaac targets
