platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

params:
  SYSTEM_DOMAIN:
  USER_ID:
  PASSWORD:
  CONFIG_DIR:
  CLIENT_SECRET:
  LOG_LEVEL:
  UAAC_SCRIPT:

run:
  path: sh
  args:
  - -ce
  - |
    uaac target "uaa.$SYSTEM_DOMAIN" --skip-ssl-validation
    echo "[DG] CLIENT SECRET - $CLIENT_SECRET"
    echo cf_mgmt_client | uaac token client get --secret="$CLIENT_SECRET"
    bash $UAAC_SCRIPT
