platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

params:
  SYSTEM_DOMAIN:

run:
  path: sh
  args:
  - -ce
  - |
    uaac target "uaa.$SYSTEM_DOMAIN" --skip-ssl-validation
    uaac targets
    uaac contexts
