platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

params:
  SYSTEM_DOMAIN:
  ENV:
  UAAC_SECRET:

run:
  path: sh
  args:
  - -ce
  - |
    uaac target "uaa.$SYSTEM_DOMAIN" --skip-ssl-validation
    echo cf_mgmt_client | uaac token client get --secret=$UAAC_SECRET
    uaac targets
    uaac contexts
