space-developer:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
space-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
space-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
enable-unassign-security-group: false
enable-remove-users: true